/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  footerNote?: string
}

export type BusinessProfile = {
  _id: string
  _type: 'businessProfile'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  email: string
  phone?: string
  address?: {
    street?: string
    postalCode?: string
    city?: string
    country?: string
  }
  socials?: Array<{
    platform: 'instagram' | 'facebook' | 'youtube' | 'linkedin' | 'tiktok'
    url: string
    _key: string
  }>
}

export type PrivacyPage = {
  _id: string
  _type: 'privacyPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  body: RichText
  updatedAt?: string
  seo?: Seo
}

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        {
          _key: string
        } & Link
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & AccessibleImage)
>

export type ImprintPage = {
  _id: string
  _type: 'imprintPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  body: RichText
  updatedAt?: string
  seo?: Seo
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  intro?: string
  successText?: string
  seo?: Seo
}

export type FaqPage = {
  _id: string
  _type: 'faqPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  intro?: string
  seo?: Seo
}

export type MagazinePage = {
  _id: string
  _type: 'magazinePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  kicker?: string
  title: string
  intro?: string
  closingTitle?: string
  closingText?: string
  cta?: Cta
  seo?: Seo
}

export type Cta = {
  _type: 'cta'
  label?: string
  link?: Link
}

export type OfferReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'offer'
}

export type OffersPage = {
  _id: string
  _type: 'offersPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  intro?: string
  order?: Array<
    {
      _key: string
    } & OfferReference
  >
  cta?: Cta
  seo?: Seo
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type FaqItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'faqItem'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  hero: {
    title: string
    text?: string
    image?: AccessibleImage
    cta?: Cta
  }
  showOffers?: boolean
  featuredOffers?: Array<
    {
      _key: string
    } & OfferReference
  >
  about?: {
    title?: string
    portrait?: AccessibleImage
    body?: RichText
    highlights?: Array<string>
  }
  showTestimonials?: boolean
  testimonials?: Array<
    {
      _key: string
    } & TestimonialReference
  >
  showFaq?: boolean
  faq?: Array<
    {
      _key: string
    } & FaqItemReference
  >
  closing?: {
    title?: string
    text?: string
    cta?: Cta
  }
  seo?: Seo
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  noIndex?: boolean
}

export type AccessibleImage = {
  _type: 'accessibleImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type ArticleBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        {
          _key: string
        } & Link
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      text: string
      _type: 'coachTip'
      _key: string
    }
  | {
      text: string
      attribution?: string
      _type: 'pullQuote'
      _key: string
    }
  | {
      image: AccessibleImage
      caption?: string
      _type: 'figure'
      _key: string
    }
  | {
      videoId: string
      title: string
      _type: 'youtubeVideo'
      _key: string
    }
>

export type Link = {
  _type: 'link'
  kind?: 'route' | 'reference' | 'external'
  route?: 'index' | 'offers' | 'magazine' | 'faq' | 'contact' | 'imprint' | 'privacy'
  reference?: OfferReference
  href?: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | OfferReference
    | TestimonialReference
    | FaqItemReference
    | PostReference
    | CategoryReference
    | AuthorReference
  language: string
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  slug: Slug
  excerpt: string
  cover?: AccessibleImage
  category?: CategoryReference
  author?: AuthorReference
  publishedAt: string
  body?: ArticleBody
  seo?: Seo
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  name: string
  role?: string
  bio?: string
  photo?: AccessibleImage
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  slug: Slug
  order: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type FaqItem = {
  _id: string
  _type: 'faqItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  question: string
  answer: RichText
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  quote: string
  author: string
  photo?: AccessibleImage
  consentConfirmed?: boolean
}

export type Offer = {
  _id: string
  _type: 'offer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  slug: Slug
  summary: string
  image?: AccessibleImage
  body?: RichText
  price?: number
  cta?: Cta
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | BusinessProfile
  | PrivacyPage
  | RichText
  | ImprintPage
  | ContactPage
  | FaqPage
  | MagazinePage
  | Cta
  | OfferReference
  | OffersPage
  | TestimonialReference
  | FaqItemReference
  | HomePage
  | SanityImageAssetReference
  | Seo
  | AccessibleImage
  | ArticleBody
  | Link
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | CategoryReference
  | AuthorReference
  | InternationalizedArrayReferenceValue
  | Post
  | Author
  | Category
  | Slug
  | FaqItem
  | Testimonial
  | Offer
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
