import { createGroqBuilder, type InferFragmentType } from 'groqd'
import { z } from 'zod'

import type {
  AccessibleImage,
  AllSanitySchemaTypes,
  Cta,
  internalGroqTypeReferenceTo,
  Link,
  Seo,
} from '~/types/sanity.types'

/**
 * The query builder: queries are written in TypeScript, checked against the Sanity schema
 * (types generated by `pnpm typegen`) and their results validated when they arrive.
 */
export const q = createGroqBuilder<{
  schemaTypes: AllSanitySchemaTypes
  referenceSymbol: typeof internalGroqTypeReferenceTo
}>()

export const imageFragment = q.fragment<AccessibleImage>().project((image) => ({
  alt: z.string(),
  url: image.field('asset').deref().field('url', z.string().nullable()),
}))

/** What the editor picked: a page, an offer (with its slug and language) or an address. */
const linkFragment = q.fragment<Link>().project((link) => ({
  kind: z.enum(['route', 'reference', 'external']).nullable(),
  route: z.string().nullable(),
  href: z.string().nullable(),
  offerSlug: link.field('reference').deref().field('slug.current', z.string().nullable()),
  offerLanguage: link.field('reference').deref().field('language', z.string().nullable()),
}))

export const ctaFragment = q.fragment<Cta>().project((cta) => ({
  label: z.string().nullable(),
  link: cta.field('link').project(linkFragment).nullable(true),
}))

export const seoFragment = q.fragment<Seo>().project((seo) => ({
  title: z.string().nullable(),
  description: z.string().nullable(),
  noIndex: z.boolean().nullable(),
  image: seo.field('image.asset').deref().field('url', z.string().nullable()),
}))

export const offerCardFragment = q.fragmentForType<'offer'>().project((offer) => ({
  id: ['_id', z.string()],
  title: z.string(),
  summary: z.string(),
  slug: ['slug.current', z.string()],
  image: offer.field('image').project(imageFragment).nullable(true),
  price: z.number().nullable(),
}))

const richTextMark = z
  .object({
    _type: z.string(),
    _key: z.string(),
    kind: z.enum(['route', 'reference', 'external']).nullish(),
    route: z.string().nullish(),
    href: z.string().nullish(),
    offerSlug: z.string().nullish(),
    offerLanguage: z.string().nullish(),
  })
  .passthrough()

const richTextBlock = z
  .object({ _type: z.string(), _key: z.string(), markDefs: z.array(richTextMark).nullish() })
  .passthrough()

/**
 * A rich-text field (Portable Text) with what the page needs added: the slug and language
 * of linked offers, the URL of images. Use it as `page.raw(...richTextField('body'))`.
 */
export const richTextField = (field: string) =>
  [
    `${field}[]{ ..., markDefs[]{ ..., "offerSlug": reference->slug.current, "offerLanguage": reference->language }, "url": asset->url }`,
    z.array(richTextBlock).nullable(),
  ] as const

export const businessFragment = q.fragmentForType<'businessProfile'>().project((business) => ({
  name: z.string(),
  email: z.string(),
  phone: z.string().nullable(),
  address: business
    .field('address')
    .project({
      street: z.string().nullable(),
      postalCode: z.string().nullable(),
      city: z.string().nullable(),
      country: z.string().nullable(),
    })
    .nullable(true),
  socials: business
    .field('socials[]')
    .project({ platform: z.string(), url: z.string() })
    .nullable(true),
}))

export type ImageData = InferFragmentType<typeof imageFragment>
export type CtaData = InferFragmentType<typeof ctaFragment>
export type SeoData = InferFragmentType<typeof seoFragment>
export type OfferCardData = InferFragmentType<typeof offerCardFragment>
export type BusinessData = InferFragmentType<typeof businessFragment>
export type RichTextData = z.infer<typeof richTextBlock>[]
